### ISSUE TITLE
Bug in Paren-x64 v2

### ISSUE THREAD

**Issue by wilbowma** [cpsc411/cpsc411-book#23]
x64 does not allow a direct int64 to memory move, only int32 to memory. Need to fix `patch-instructions` spec.
```
 (let ([x `(module (let ([x ,(max-int 64)]) x))])
            (test-case "set var to max int 64" (check-confluent?/upto (execute x) (interp-values-lang x) (max-int 64))))
```

**Comment by wilbowma** [comment]
Fixed in language specs; should review chapters

**Comment by skeuchel** [comment]
Is there a related bug in Paren-x64 v4? The [grammar](https://www.students.cs.ubc.ca/~cs-411/2020w2/chp4_book_top.html#%28def._%28%28lib._cpsc411%2Flangs%2Fv4..rkt%29._paren-x64-v4%29%29) has the following productions
```
s    ::=  (set! addr trg) | ...
trg  ::=  reg | label
```
Shouldn't the int64 restrictions also apply to labels?

**Comment by wilbowma** [comment]
Ah probably. Will check; thanks!

**Comment by wilbowma** [comment]
Apparently not: https://godbolt.org/z/o13cYs

**Comment by wilbowma** [comment]
Looks like it does become a problem if use rip-relative addressing: https://godbolt.org/z/rEjKvn

Should probably restrict the grammar, since we'll need to move to RIP-relative for macOS support.

**Comment by wilbowma** [comment]
Added a `rip-relative` branch in the private repo with largely untested updates to the reference compiler, but need to update grammars and book.

**Comment by skeuchel** [comment]
Just to follow up on the labels in v4. The System V ABI for AMD64 specifies a **small code model** that essentially says that symbols are in the lower 32-bit virtual address range. So it doesn't hit the restriction for immediates in that model.

**Comment by wilbowma** [comment]
Think this is now fixed and explained in the most recent 2021w2 commit
