### ISSUE TITLE
Typos in 4.2: Abstacting-Boilerplate

### ISSUE THREAD

**Issue by atgeller** [cpsc411/cpsc411-book#3]
Legend: `additions`, ~subtractions~

Some of these are less certain than others :)

https://github.com/cpsc411/cpsc411-book/blob/c7fbcd41bbc04c34552e4521047d25328ab6f89d/chapter/abstracting-boilerplate.scrbl#L35
"error prone`,` ~or~ software design being complex, `or` software produced"

https://github.com/cpsc411/cpsc411-book/blob/c7fbcd41bbc04c34552e4521047d25328ab6f89d/chapter/abstracting-boilerplate.scrbl#L39
"high learning curve`,`"

https://github.com/cpsc411/cpsc411-book/blob/c7fbcd41bbc04c34552e4521047d25328ab6f89d/chapter/abstracting-boilerplate.scrbl#L40
I don't like that "and" on its own, I would go for either: "identify one, and `then` design" or "identify one, ~and~ `then` design"

https://github.com/cpsc411/cpsc411-book/blob/c7fbcd41bbc04c34552e4521047d25328ab6f89d/chapter/abstracting-boilerplate.scrbl#L48
"error`-`prone"

https://github.com/cpsc411/cpsc411-book/blob/c7fbcd41bbc04c34552e4521047d25328ab6f89d/chapter/abstracting-boilerplate.scrbl#L56
"instructions sequence~,~`:` lists of instructions"

https://github.com/cpsc411/cpsc411-book/blob/c7fbcd41bbc04c34552e4521047d25328ab6f89d/chapter/abstracting-boilerplate.scrbl#L64
“first executes the instructions `in` p_1 and then executes the instructions _in_ p_2” 

https://github.com/cpsc411/cpsc411-book/blob/c7fbcd41bbc04c34552e4521047d25328ab6f89d/chapter/abstracting-boilerplate.scrbl#L67 - "we need `to` define"

https://github.com/cpsc411/cpsc411-book/blob/c7fbcd41bbc04c34552e4521047d25328ab6f89d/chapter/abstracting-boilerplate.scrbl#L68
“the meaning `of` instruction sequence”

https://github.com/cpsc411/cpsc411-book/blob/c7fbcd41bbc04c34552e4521047d25328ab6f89d/chapter/abstracting-boilerplate.scrbl#L74
“instruction`s`”

https://github.com/cpsc411/cpsc411-book/blob/c7fbcd41bbc04c34552e4521047d25328ab6f89d/chapter/abstracting-boilerplate.scrbl#L89
“or a value `in` one register”

https://github.com/cpsc411/cpsc411-book/blob/c7fbcd41bbc04c34552e4521047d25328ab6f89d/chapter/abstracting-boilerplate.scrbl#L286
“~these takes~”

https://github.com/cpsc411/cpsc411-book/blob/c7fbcd41bbc04c34552e4521047d25328ab6f89d/chapter/abstracting-boilerplate.scrbl#L306
More of a clarity thing, but I would add a comma: “which every valid instruction has`,` and which has quite simple typing rules”
Also, does a type have typing rules? I guess so? IDK

https://github.com/cpsc411/cpsc411-book/blob/c7fbcd41bbc04c34552e4521047d25328ab6f89d/chapter/abstracting-boilerplate.scrbl#L333
“prov`a`bly”

https://github.com/cpsc411/cpsc411-book/blob/c7fbcd41bbc04c34552e4521047d25328ab6f89d/chapter/abstracting-boilerplate.scrbl#L330
“functions~,~ to enable”

https://github.com/cpsc411/cpsc411-book/blob/c7fbcd41bbc04c34552e4521047d25328ab6f89d/chapter/abstracting-boilerplate.scrbl#L335
“responsible ~to~ `for` enforcing”

https://github.com/cpsc411/cpsc411-book/blob/c7fbcd41bbc04c34552e4521047d25328ab6f89d/chapter/abstracting-boilerplate.scrbl#L371
“it~’~s”

https://github.com/cpsc411/cpsc411-book/blob/c7fbcd41bbc04c34552e4521047d25328ab6f89d/chapter/abstracting-boilerplate.scrbl#L436
“Register machine~,~`:` a recursive function”

https://github.com/cpsc411/cpsc411-book/blob/c7fbcd41bbc04c34552e4521047d25328ab6f89d/chapter/abstracting-boilerplate.scrbl#L437
“interprets each instruction~s~”

https://github.com/cpsc411/cpsc411-book/blob/c7fbcd41bbc04c34552e4521047d25328ab6f89d/chapter/abstracting-boilerplate.scrbl#L605
“design`ed` the compiler”

**Comment by wilbowma** [comment]
Can you make a PR and I'll merge the ones I agree with?

**Comment by atgeller** [comment]
Done: https://github.com/cpsc411/cpsc411-book/pull/4

**Comment by wilbowma** [comment]
closed via cdce2842d79a38083f84efc3010e64137a74540e
