### ISSUE TITLE
Typos in Ch. 4.5 - Register Allocation

### ISSUE THREAD

**Issue by i6s1b** [cpsc411/cpsc411-book#39]
- https://github.com/cpsc411/cpsc411-book/blob/1fcf71d38b6ec19c3fe85dbfb8b57b788885f748/chapter/register-allocation.scrbl#L80
  - "magintude" should be "mag**ni**tude".
- https://github.com/cpsc411/cpsc411-book/blob/1fcf71d38b6ec19c3fe85dbfb8b57b788885f748/chapter/register-allocation.scrbl#L202
  - "change the value of the variable" should be "change**s** the value of the variable"
- https://github.com/cpsc411/cpsc411-book/blob/1fcf71d38b6ec19c3fe85dbfb8b57b788885f748/chapter/register-allocation.scrbl#L235
  - Odd wording - maybe it should read "We start by assuming" instead
- https://github.com/cpsc411/cpsc411-book/blob/1fcf71d38b6ec19c3fe85dbfb8b57b788885f748/chapter/register-allocation.scrbl#L262
  - "mirror structure" should be "mirror **the** structure"
- https://github.com/cpsc411/cpsc411-book/blob/1fcf71d38b6ec19c3fe85dbfb8b57b788885f748/chapter/register-allocation.scrbl#L279
  - "for for" should be "for"
- https://github.com/cpsc411/cpsc411-book/blob/1fcf71d38b6ec19c3fe85dbfb8b57b788885f748/chapter/register-allocation.scrbl#L297
  - "undead-set tree a new info field" should be "undead-set tree **in** a new info field"
- https://github.com/cpsc411/cpsc411-book/blob/1fcf71d38b6ec19c3fe85dbfb8b57b788885f748/chapter/register-allocation.scrbl#L378
  - (Suggestion) Add some kind of delimiter after "True Definition of Conflict"? (e.g. `:`)
  - ![](https://i.ibb.co/cN9T2jg/Screenshot-2021-02-23-091657.png)
- https://github.com/cpsc411/cpsc411-book/blob/1fcf71d38b6ec19c3fe85dbfb8b57b788885f748/chapter/register-allocation.scrbl#L386
  - "We also do not know variables are" should be "We also do not know **which** variables are"
- https://github.com/cpsc411/cpsc411-book/blob/1fcf71d38b6ec19c3fe85dbfb8b57b788885f748/chapter/register-allocation.scrbl#L394
  - "already approximate liveness via undead-out sets, so what reminds" should be "already approximate**d** liveness via undead-out sets, so what rem**ain**s"
- https://github.com/cpsc411/cpsc411-book/blob/1fcf71d38b6ec19c3fe85dbfb8b57b788885f748/chapter/register-allocation.scrbl#L399
  - "variables as represented" should be "variables a**re** represented"
- https://github.com/cpsc411/cpsc411-book/blob/1fcf71d38b6ec19c3fe85dbfb8b57b788885f748/chapter/register-allocation.scrbl#L400
  - Odd wording in "conflicts between variables are represented as an edge the variable to each of the variables in the associated set"
- https://github.com/cpsc411/cpsc411-book/blob/1fcf71d38b6ec19c3fe85dbfb8b57b788885f748/chapter/register-allocation.scrbl#L404
  - "set variables" should be "set **of** variables"
- https://github.com/cpsc411/cpsc411-book/blob/1fcf71d38b6ec19c3fe85dbfb8b57b788885f748/chapter/register-allocation.scrbl#L422
  - "as any variables" should be "as any **other variable**"
- https://github.com/cpsc411/cpsc411-book/blob/1fcf71d38b6ec19c3fe85dbfb8b57b788885f748/chapter/register-allocation.scrbl#L425
  - (Suggestion) "would have been" could be "would **be**"
- https://github.com/cpsc411/cpsc411-book/blob/1fcf71d38b6ec19c3fe85dbfb8b57b788885f748/chapter/register-allocation.scrbl#L455
  - "field extended with" should be "field **is** extended with"
- https://github.com/cpsc411/cpsc411-book/blob/1fcf71d38b6ec19c3fe85dbfb8b57b788885f748/chapter/register-allocation.scrbl#L462
  - "traverse an program" should be "traverse **a** program"
- https://github.com/cpsc411/cpsc411-book/blob/1fcf71d38b6ec19c3fe85dbfb8b57b788885f748/chapter/register-allocation.scrbl#L463
  - "analysis each instruction" should be "**analyze** each instruction"
- https://github.com/cpsc411/cpsc411-book/blob/1fcf71d38b6ec19c3fe85dbfb8b57b788885f748/chapter/register-allocation.scrbl#L465
  - "an graph" should be "**a** graph"
- https://github.com/cpsc411/cpsc411-book/blob/1fcf71d38b6ec19c3fe85dbfb8b57b788885f748/chapter/register-allocation.scrbl#L530
  - "as in the, the step the actually assigns" should be "as in the **step that** actually assigns"
- https://github.com/cpsc411/cpsc411-book/blob/1fcf71d38b6ec19c3fe85dbfb8b57b788885f748/chapter/register-allocation.scrbl#L536
  - "fit in register" should be "fit in register**s**"
- https://github.com/cpsc411/cpsc411-book/blob/1fcf71d38b6ec19c3fe85dbfb8b57b788885f748/chapter/register-allocation.scrbl#L553
  - "producing an" should be "produc**e** an"
- https://github.com/cpsc411/cpsc411-book/blob/1fcf71d38b6ec19c3fe85dbfb8b57b788885f748/chapter/register-allocation.scrbl#L564
  - "some for pre-defined" should be "**for some** pre-defined"
- https://github.com/cpsc411/cpsc411-book/blob/1fcf71d38b6ec19c3fe85dbfb8b57b788885f748/chapter/register-allocation.scrbl#L567
  - (Suggestion) consider changing "removed from the input set and removed from the conflict graph" to "removed from the input set and **the conflict graph**"
- https://github.com/cpsc411/cpsc411-book/blob/1fcf71d38b6ec19c3fe85dbfb8b57b788885f748/chapter/register-allocation.scrbl#L577
  - "select a register, then" should be "select**ing** a register,"
- https://github.com/cpsc411/cpsc411-book/blob/1fcf71d38b6ec19c3fe85dbfb8b57b788885f748/chapter/register-allocation.scrbl#L579
  - "choosen" should be "ch**o**sen"
- https://github.com/cpsc411/cpsc411-book/blob/1fcf71d38b6ec19c3fe85dbfb8b57b788885f748/chapter/register-allocation.scrbl#L593
  - "regsiter allocator" should be "reg**is**ter allocator"

These lines have the same "typo":

- https://github.com/cpsc411/cpsc411-book/blob/1fcf71d38b6ec19c3fe85dbfb8b57b788885f748/chapter/register-allocation.scrbl#L561
- https://github.com/cpsc411/cpsc411-book/blob/1fcf71d38b6ec19c3fe85dbfb8b57b788885f748/chapter/register-allocation.scrbl#L563
- https://github.com/cpsc411/cpsc411-book/blob/1fcf71d38b6ec19c3fe85dbfb8b57b788885f748/chapter/register-allocation.scrbl#L567

Here, "abstract locations" should be "abstract **location**." But because `abstract locations` is hyperlinked, not sure if this can be fixed.

**Comment by wilbowma** [comment]
Thanks!
