### ISSUE TITLE
Typos in Ch. 4.6 - Structured Control Flow

### ISSUE THREAD

**Issue by i6s1b** [cpsc411/cpsc411-book#40]
# 4.6.1

No typos in this section.

&nbsp;

# 4.6.2

- https://github.com/cpsc411/cpsc411-book/blob/9786b249cbaa95ce96a6214fcf426a8a37b267af/chapter/structured-control.scrbl#L138
  - "proceed designing" should be "proceed **to** designing"
- https://github.com/cpsc411/cpsc411-book/blob/9786b249cbaa95ce96a6214fcf426a8a37b267af/chapter/structured-control.scrbl#L150
  - Something is wrong with this sentence: "predicate is one of a comparison between two values must appear in the predicate position"
- https://github.com/cpsc411/cpsc411-book/blob/9786b249cbaa95ce96a6214fcf426a8a37b267af/chapter/structured-control.scrbl#L172
  - "solve the problems" should be "solve the **problem**"

&nbsp;

# 4.6.3

- https://github.com/cpsc411/cpsc411-book/blob/9786b249cbaa95ce96a6214fcf426a8a37b267af/chapter/structured-control.scrbl#L191
  - "same instructions" should be "same **instruction**"
- https://github.com/cpsc411/cpsc411-book/blob/9786b249cbaa95ce96a6214fcf426a8a37b267af/chapter/structured-control.scrbl#L232
  - (Suggestion) "condition jump" could be "condition**al** jump"
- https://github.com/cpsc411/cpsc411-book/blob/9786b249cbaa95ce96a6214fcf426a8a37b267af/chapter/structured-control.scrbl#L239
  - "Each corresponds" should be "**e**ach corresponds"

## 4.6.3.1

- https://github.com/cpsc411/cpsc411-book/blob/9786b249cbaa95ce96a6214fcf426a8a37b267af/chapter/structured-control.scrbl#L286
  - "thus language, design problem" should be "thus, **a language design** problem"
- https://github.com/cpsc411/cpsc411-book/blob/9786b249cbaa95ce96a6214fcf426a8a37b267af/chapter/structured-control.scrbl#L291
  - "operating systems linker" should be "operating system**'**s linker"
- https://github.com/cpsc411/cpsc411-book/blob/9786b249cbaa95ce96a6214fcf426a8a37b267af/chapter/structured-control.scrbl#L296
  - (Comment) Not sure why the first letters of the word "run-time" are emphasized. Looks rather odd. If the goal was to hint to the reader what `rt` stands for in `Paren-x64-rt v4`, I think an explicit note should be made instead.
- https://github.com/cpsc411/cpsc411-book/blob/9786b249cbaa95ce96a6214fcf426a8a37b267af/chapter/structured-control.scrbl#L324
  - "give a semantics" should be "give **semantics**" or "give a **semantic**"
  - Note that this typo appears twice on this line
- https://github.com/cpsc411/cpsc411-book/blob/9786b249cbaa95ce96a6214fcf426a8a37b267af/chapter/structured-control.scrbl#L341
  - There are inconsistencies in variable naming here. In `defproc`, the variable names are `c` and `m`, whereas in its purpose statement, the variable names are `code` and `memory`
- https://github.com/cpsc411/cpsc411-book/blob/9786b249cbaa95ce96a6214fcf426a8a37b267af/chapter/structured-control.scrbl#L350
  - Odd wording - I think "execution as position in the list `code`" should be "execut**ed** as **the** position in the `code`"

## 4.6.3.2

- https://github.com/cpsc411/cpsc411-book/blob/9786b249cbaa95ce96a6214fcf426a8a37b267af/chapter/structured-control.scrbl#L355
  - "Having exposing" should be "Having expos**ed**"
- https://github.com/cpsc411/cpsc411-book/blob/9786b249cbaa95ce96a6214fcf426a8a37b267af/chapter/structured-control.scrbl#L357
  - "introducing a" should be "introduc**e** a"
- https://github.com/cpsc411/cpsc411-book/blob/9786b249cbaa95ce96a6214fcf426a8a37b267af/chapter/structured-control.scrbl#L364
  - (Suggestion) Although not grammatically incorrect in its current form, changing "these abstract" to "these **languages** abstract" will help make it more obvious to the reader what's being discussed here.
- https://github.com/cpsc411/cpsc411-book/blob/9786b249cbaa95ce96a6214fcf426a8a37b267af/chapter/structured-control.scrbl#L376
  - `Paren-x64-fvars v4` is not hyperlinked
- https://github.com/cpsc411/cpsc411-book/blob/9786b249cbaa95ce96a6214fcf426a8a37b267af/chapter/structured-control.scrbl#L393
  - `Paren-asm-lang v4` is not hyperlinked. Seeing how `Paren-x64-fvars v4` above was also not hyperlinked, maybe this was intended?
- https://github.com/cpsc411/cpsc411-book/blob/9786b249cbaa95ce96a6214fcf426a8a37b267af/chapter/structured-control.scrbl#L411
  - (Question) Is the single quote in the label `'done` intended?
- https://github.com/cpsc411/cpsc411-book/blob/9786b249cbaa95ce96a6214fcf426a8a37b267af/chapter/structured-control.scrbl#L435
  - "into to a sequence of instructions and an auxiliary register" should be "into ~~to~~ a sequence of instructions ~~and~~ **using** auxiliary register**s**"

&nbsp;

# 4.6.4

- https://github.com/cpsc411/cpsc411-book/blob/9786b249cbaa95ce96a6214fcf426a8a37b267af/chapter/structured-control.scrbl#L444
  - "family of language of languages" should be "family of ~~language of~~ languages"
- https://github.com/cpsc411/cpsc411-book/blob/9786b249cbaa95ce96a6214fcf426a8a37b267af/chapter/structured-control.scrbl#L453
  - "continuing to propagate" should be "continu**e** to propagate"
- https://github.com/cpsc411/cpsc411-book/blob/9786b249cbaa95ce96a6214fcf426a8a37b267af/chapter/structured-control.scrbl#L491
  - "exit the end" should be "exit **at** the end"
- https://github.com/cpsc411/cpsc411-book/blob/9786b249cbaa95ce96a6214fcf426a8a37b267af/chapter/structured-control.scrbl#L494
  - "on entry and exit to a" should be "on entry and **on** exit ~~to~~ **of** a"
- https://github.com/cpsc411/cpsc411-book/blob/9786b249cbaa95ce96a6214fcf426a8a37b267af/chapter/structured-control.scrbl#L524
  - "ends three instruction sequence" should be "ends **in** three instruction sequence**s**"
- https://github.com/cpsc411/cpsc411-book/blob/9786b249cbaa95ce96a6214fcf426a8a37b267af/chapter/structured-control.scrbl#L539
  - "exectuion" should be "exec**ut**ion"

## 4.6.4.1

- https://github.com/cpsc411/cpsc411-book/blob/9786b249cbaa95ce96a6214fcf426a8a37b267af/chapter/structured-control.scrbl#L570
  - (Suggestion) We can do away with "although" in "although it’s less obvious"

## 4.6.4.2

- https://github.com/cpsc411/cpsc411-book/blob/9786b249cbaa95ce96a6214fcf426a8a37b267af/chapter/structured-control.scrbl#L637
  - "simply the" should be "simpl**if**y the"
- https://github.com/cpsc411/cpsc411-book/blob/9786b249cbaa95ce96a6214fcf426a8a37b267af/chapter/structured-control.scrbl#L640
  - Odd wording - should rephrase the sentence "exposing only an if expression, there is no point (yet) to exposing jumps further up the pipeline"
- https://github.com/cpsc411/cpsc411-book/blob/9786b249cbaa95ce96a6214fcf426a8a37b267af/chapter/structured-control.scrbl#L656
  - "arbitrarily nesting" should be "arbitrarily nest**ed**"
- https://github.com/cpsc411/cpsc411-book/blob/9786b249cbaa95ce96a6214fcf426a8a37b267af/chapter/structured-control.scrbl#L717
  - "an imperative programming languages" should be "an imperative programming language~~s~~"
- https://github.com/cpsc411/cpsc411-book/blob/9786b249cbaa95ce96a6214fcf426a8a37b267af/chapter/structured-control.scrbl#L726
  - (Suggestion) "duplicate code," could be ended with a semicolon instead ("duplicate code~~,~~**;**") to allow better logical flow of the sentence
- https://github.com/cpsc411/cpsc411-book/blob/9786b249cbaa95ce96a6214fcf426a8a37b267af/chapter/structured-control.scrbl#L735
  - "nested `if` expressions" should be "nested `if` expression~~s~~"
- https://github.com/cpsc411/cpsc411-book/blob/9786b249cbaa95ce96a6214fcf426a8a37b267af/chapter/structured-control.scrbl#L740
  - "we need takes" should be "we need **to** take~~s~~"
- https://github.com/cpsc411/cpsc411-book/blob/9786b249cbaa95ce96a6214fcf426a8a37b267af/chapter/structured-control.scrbl#L791
  - "predicate determine" should be "predicate **to** determine"
- https://github.com/cpsc411/cpsc411-book/blob/9786b249cbaa95ce96a6214fcf426a8a37b267af/chapter/structured-control.scrbl#L793
  - "and to" should be "and ~~to~~ **that**"

&nbsp;

# 4.6.5

- https://github.com/cpsc411/cpsc411-book/blob/9786b249cbaa95ce96a6214fcf426a8a37b267af/chapter/structured-control.scrbl#L824
  - "as single compiler" should be "as **a** single compiler"

## 4.6.5.1

- https://github.com/cpsc411/cpsc411-book/blob/9786b249cbaa95ce96a6214fcf426a8a37b267af/chapter/structured-control.scrbl#L842
  - "if" should be stylized as code (i.e. `if`)

## 4.6.5.2

- https://github.com/cpsc411/cpsc411-book/blob/9786b249cbaa95ce96a6214fcf426a8a37b267af/chapter/structured-control.scrbl#L905
  - "undead sets" should be "undead set~~s~~"

## 4.6.5.3

No typos in this section.

## 4.6.5.4

No typos in this section.

## 4.6.5.5

- https://github.com/cpsc411/cpsc411-book/blob/9786b249cbaa95ce96a6214fcf426a8a37b267af/chapter/structured-control.scrbl#L1013
  - "the assignment" should be "the assignment**s**"

&nbsp;

# 4.6.6

- https://github.com/cpsc411/cpsc411-book/blob/9786b249cbaa95ce96a6214fcf426a8a37b267af/chapter/structured-control.scrbl#L1058
  - "is simple" should be "is **a** simple"
- https://github.com/cpsc411/cpsc411-book/blob/9786b249cbaa95ce96a6214fcf426a8a37b267af/chapter/structured-control.scrbl#L1090
  - "are still not" should be "~~are~~ **is** still not"
- https://github.com/cpsc411/cpsc411-book/blob/9786b249cbaa95ce96a6214fcf426a8a37b267af/chapter/structured-control.scrbl#L1091
  - "abstract location" should be "abstract location**s**"
- https://github.com/cpsc411/cpsc411-book/blob/9786b249cbaa95ce96a6214fcf426a8a37b267af/chapter/structured-control.scrbl#L1105
  - "introduced" should be "introduce~~d~~"

&nbsp;

# 4.6.7

No typos in this section.

**Comment by wilbowma** [comment]
> "give a semantics" should be "give semantics" or "give a semantic"
Nope; semantics is both singular and plural. Don't blame me.
