### ISSUE TITLE
Confusing typo in 4.8 Procedural Abstraction: Return

### ISSUE THREAD

**Issue by atgeller** [cpsc411/cpsc411-book#44]
https://github.com/cpsc411/cpsc411-book/blob/01e0a17fc2b995fd4aaf5a6083c1fa358d88fd38/chapter/return.scrbl#L1399
This sentence is rather confusing, especially since the increment and decrement operations shown here are the same: `(set! fbp (- fbp 24))` and `(set! fbp (- fbp 24))`. The parenthetical, `((- (* 3 (current-word-size-bytes)) 24))`, is also rather confusing in terms of what it is referring to and what it means.

**Comment by wilbowma** [comment]
Fixed in a8c11a3eedb11f088de119b72eda4c628d3bd6ed
