### ISSUE TITLE
Confusing paragraph in 4.10.2.4

### ISSUE THREAD

**Issue by atgeller** [cpsc411/cpsc411-book#56]
https://github.com/cpsc411/cpsc411-book/blob/f2199857fe0b894ac5216775c5e6036f5fb0a8f2/chapter/structured-data.scrbl#L310

"We want to do this after the passes that analyze physical locations" and "however, we want to do this before we abstract away from all machine details" are confusing because in terms of the [compiler pipeline](https://www.students.cs.ubc.ca/~cs-411/2020w2/chp-structured-data_book_top.html#%28part._sec~3aoverview%29), `expose-allocation-pointer` comes _before_ the passes that analyze physical locations and _after_ the passes that moves from abstractions to machine details where registers are introduced registers.

I think what is confusing is that this milestone is written bottom up, where each pass is moving from low-level to high-level, unlike say milestone 5 which is the other direction, so the meaning of "before" and "after" may not be intuitive.

**Comment by wilbowma** [comment]
Rewrote the entire chapter top-down, which I think addresses this problem.
