### ISSUE TITLE
Missing example for frame variables in call-undead 

### ISSUE THREAD

**Issue by wilbowma** [cpsc411/cpsc411-book#59]
(from @skeuchel on private repo)
The chapter 4.8.6.3 Frame Allocation on `assign-call-undead-variables` reads the following

> The size of a frame n (in slots) for a given non-tail call is one more than the maximum of:
>   * [...]
>   * the index of the largest frame location in the undead-out set for the non-tail call.
>   [...] Since we’re allowing physical locations in our source language, we could have a frame variable live after a call, and must preserve up to that index.

Could you add an example that shows frame variables in the call-undead set? I haven't been able to come up with one myself. I have tried to introduce frame variables using a tail call, which is one (maybe at this stage the only) way to introduce physical frame locations. But those will be dead at any non-tail call before the tail call.

**Comment by wilbowma** [comment]
With the current compiler design, I don't think frame variables will show up syntactically in the `call-undead` sets.

Here's a short program that requires `fv1` and `fv0` *semantically* in the `call-undead` set
for `add`:

```
(parameterize ([current-pass-list
                (list
                 check-values-lang
                 uniquify
                 sequentialize-let
                 impose-calling-conventions
                 canonicalize-bind
                 select-instructions
                 uncover-locals
                 undead-analysis
                 conflict-analysis
                 assign-call-undead-variables)])
  (compile
   '(module
        (define add (lambda (x y) (let ([x (call add1 x)]) (+ x y))))
        (define add1 (lambda (x) (+ 1 x)))
      (call add 7 8))))
```

```racket
'(module
   ....
   (define L.add.10
     ((new-frames (()))
      (locals (x.54 x.55))
      (call-undead (y.53 tmp-ra.57))
      (conflicts
       ((tmp-ra.57 (rax x.55 y.53 x.54 rbp rsi rdi))
        (x.54 (y.53 rbp tmp-ra.57 rsi))
        (y.53 (rax x.55 rbp tmp-ra.57 x.54))
        (x.55 (rbp tmp-ra.57 y.53))))
      (assignment ((tmp-ra.57 fv0) (y.53 fv1))))
     (begin
       (set! tmp-ra.57 r15)
       (set! x.54 rdi)
       (set! y.53 rsi)
       (return-point L.rp.12
         (begin
           (set! rdi x.54)
           (set! r15 L.rp.12)
           (jump L.add1.11 rbp r15 rdi)))
       (set! x.55 rax)
       (set! rax x.55)
       (set! rax (+ rax y.53))
       (jump tmp-ra.57 rbp rax)))
  ....)
```

Note that the frame variables do not appear syntacically in the `call-undead` set,
but only semantically.
However, because all of these passses take place in the same "language", `Asm-pred-lang`,
(or at least the same family of languages `Asm-pred-lang/*`), the following
equivalent optimized program ought to be supported:

```racket
'(module
   ....
   (define L.add.10
     ((new-frames (()))
      (locals (x.54 x.55))
      (call-undead (fv1 fv0))
      (conflicts
       ((x.54 (fv1 rbp fv0 rsi))
        (x.55 (rbp fv0 fv1))))
      (assignment ()))
     (begin
       (set! fv0 r15)
       (set! x.54 rdi)
       (set! fv1 rsi)
       (return-point L.rp.12
         (begin
           (set! rdi x.54)
           (set! r15 L.rp.12)
           (jump L.add1.11 rbp r15 rdi)))
       (set! x.55 rax)
       (set! rax x.55)
       (set! rax (+ rax fv1))
       (jump fv0 rbp rax)))
   ....)
```

This optimized IR program would improve the performance of
register allocation, whose algorithmic complexity is bounded by the number
of vertexes in the conflict graph, so reducing the number of vertexes.

**Comment by skeuchel** [comment]
Thanks for the clarification. I found the optimization argument convincing enough, even though there is no such pass at the moment. Such a hypothetical pass should of course not introduce registers into the call-undead set..
