### ISSUE TITLE
Off by one error in frame allocation?

### ISSUE THREAD

**Issue by skeuchel** [cpsc411/cpsc411-book#60]
One more thing in frame allocation. It states

> The size of a frame n (in slots) for a given non-tail call is one more than the maximum of:
> - the number of locations in the undead-out set for the non-tail call, or
> - the index of the largest frame location in the undead-out set for the non-tail call.

Why the "one more" for both? Instead of `1+max(numlocs,maxindex)`, shouldn't it be `max(numlocs,1+maxindex)`?

**Comment by skeuchel** [comment]
It's probably less important because that number is not really computed/used in the compiler at this stage. Instead the size of the frame is calculated after `assign-call-undead-variables` at which point looking at the indices is enough.

**Comment by wilbowma** [comment]
I think you're right; the number of locations is already while 1-indexed while the index is 0-indexed.

**Comment by wilbowma** [comment]
Fixed in revising return branch
