### ISSUE TITLE
Inconsistently structured undead-out set tree after `allocate-frames` in `Asm-pred-lang-v6/framed`

### ISSUE THREAD

**Issue by skeuchel** [cpsc411/cpsc411-book#61]
The `allocate-frames` pass changes the program by adjusting the `fbp` before and after a non-tail call. However, the undead-out tree is not updated, so the structure of the tree does not correspond to the program anymore. It should be safe to drop it at this stage, because the conflict graph for register allocation has already been computed.

**Comment by wilbowma** [comment]
Related to #50

**Comment by wilbowma** [comment]
Fixed in 2021w2 branch
